# Generated by Django 3.1.2 on 2020-11-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201101_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_olx_published',
            field=models.BooleanField(default=False),
        ),
    ]
