# Generated by Django 3.0.4 on 2020-03-29 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 15, 36, 59, 677089, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_create',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_modify',
            field=models.IntegerField(null=True),
        ),
    ]
