# Generated by Django 3.0.4 on 2020-03-29 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200329_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 15, 49, 44, 46116, tzinfo=utc)),
        ),
    ]
