# Generated by Django 3.0.7 on 2020-06-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200621_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('0', 'DRAFT'), ('1', 'PUBLISHED')], max_length=1, null=True),
        ),
    ]
